---
- name: Converge
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  pre_tasks:
    - debug:
        msg: "{{ ansible_user_id }} ::: {{ ansible_user }}"
  roles:
    - travis_freebsd_ansible
