---
- name: Converge
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - debug:
        msg: "{{ ansible_user_id }} ::: {{ ansible_user }}"
    - import_role:
        name: "travis-freebsd-ansible"
