---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    driver: kvm
    options:
      memory: 2048
      cpus: 2
lint: |
  set -e
  yamllint .
  prettier --check --parser yaml "**/*.yml"
  ansible-lint
platforms:
  - name: instance
    box: ${MOLECULE_DISTRO_BOX:-"roboxes/freebsd12"}
    interfaces:
      - network_name: public_network
        dev: "virbr0"
        type: "bridge"
        mode: "bridge"
provisioner:
  name: ansible
  sudo: True
  log: True
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
